version: '3'
services:
  angular-app:  
    build: ./frontend
    container_name: angular-app
    ports:
      - 4200:80
    links:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - app-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  spring-app:
    build: ./backend
    container_name: spring-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - 8080:8080 
    links:
      - angular-app


volumes:
  app-data:
