version: '3'
services:
  angular-app:  
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: angular
    ports:
      - 4200:80
    networks:
      - backend-net

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend-net


  spring-app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: spring
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - 8080:8080 
    networks:
      - backend-net

  
networks:
  backend-net:
    driver: bridge