
spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  devtools:
    restart:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: create

jwt:
  secret: YYRq+Y6myo81mBwrJ+oTKeBPhcH1NT2nf6HwVJrGuf09d17vxz4ZRwmipXt4qv2z4fLEw99BNS3AdrLHK/K/LA==


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
logging:
  level:
    org:
      springframework:
        security: TRACE
        aop: TRACE